FROM conjurdemos/chefconf15-foundation

WORKDIR /

ADD conjurers  /etc/sudoers.d/conjurers
ADD .conjurenv /.conjurenv
ADD upload-all /usr/local/bin/upload-all
ADD list-all   /usr/local/bin/list-all
ADD knife.rb   /etc/chef/knife.rb
